# Site settings
title:  Data Design Standards
baseURL: 127.0.0.1 

# this ensure that posts with future dates are published
future: true

encoding: utf-8

repos:
- name: Data Design Standards
  description: Main repository for the Data Design Standards
  url: https://github.com/18F/uswds-data
- name: U.S. Web Design Standards
  description: Main repository for the U.S. Web Design Standards package
  url: https://github.com/18F/web-design-standards

sass:
  load_paths:
    - css
    - assets/css

collections:
  components:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: ''
      type: components
    values:
      layout: component
  - scope:
      path: ''
      type: posts
    values:
      layout: post

# Build settings
markdown: redcarpet
redcarpet:
  extensions:
    - smart
    - tables
    - with_toc_data # automatic heading ids

gems:
  - jekyll-redirect-from

exclude:
  - ".ruby-version"
  - ".sass-cache"
  - CONTRIBUTING.md
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - config
  - js
  - vendor
  - manifest.yml
  - node_modules
  - package.json
  - gulpfile.js
  - circle.yml
