title: U.S. Web Design Standards Data Visualization Guide
exclude:
  # top-level log
  - '*.log'
  # package manager lock files
  - '*.lock'
  # other scripts
  - '*.sh'
  # markdown files
  - CONTRIBUTING.md
  - LICENSE.md
  - README.md
  # node depenencies
  - node_modules
  - package.json
  # ruby dependencies
  - Gemfile
  # docker stuff
  - Dockerfile
  - 'docker-*.yml'
  # circleCI stuff
  - vendor
