version: '2'
services:
  app:
    build: .
    volumes:
      - .:/uswds-data
      - node-modules:/uswds-data/node_modules/
      - root:/root/
    environment:
      - REMOTE_CHROME_URL=http://chrome:9222
      - PORT=4000
    working_dir: /uswds-data
    command: yarn start
    ports:
      - 4000:4000
    stop_signal: SIGKILL
  chrome:
    image: yukinying/chrome-headless-browser:61.0.3141.7
    cap_add:
      - SYS_ADMIN
    stop_signal: SIGKILL
volumes:
  node-modules:
  root:
